language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.5
# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: 
  - python runtests.py
